name: mahmoud
description: Flutter Course.
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.1.3 <4.0.0'


dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6
  quick_actions: ^1.0.6
  dio: ^5.4.0
  image_picker: ^1.0.4
  video_player: ^2.8.1
  flutter_pdfview: ^1.3.2
  just_audio: ^0.9.36
  file_picker: ^6.1.1
  flutter_sound: ^9.2.13
  path_provider: ^2.1.1
  hexcolor: ^3.0.1



  dropdown_search: ^5.0.6
















dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1


flutter:
  generate: true
  uses-material-design: true


  assets:
    - assets/