name: mahmoud
description: Flutter Course.
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.3.4 <4.0.0'


dependencies:
  flutter:
    sdk: flutter
  high_q_paginated_drop_down: ^2.1.0
  cupertino_icons: ^1.0.8
  quick_actions: ^1.0.7
  dio: ^5.5.0+1
  image_picker: ^1.1.2
  video_player: ^2.9.1
  flutter_pdfview: ^1.3.2
  just_audio: ^0.9.39
  file_picker: ^8.0.6
  flutter_sound: ^9.9.5
  path_provider: ^2.1.4
  hexcolor: ^3.0.1
  dropdown_search: ^5.0.6
  badges: ^3.1.2

















dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0


flutter:
  generate: true
  uses-material-design: true


  assets:
    - assets/